# Understory for Kitty
background              #181B16
foreground              #D8D2C4
selection_background    #3F5B3A
selection_foreground    #F0EBDD
cursor                  #8EAD73
cursor_text_color       #181B16
url_color               #6E9B85

color0   #20251D
color1   #B8645B
color2   #66845A
color3   #C59B58
color4   #668F92
color5   #88768F
color6   #6E9B85
color7   #BDB7AA
color8   #5C6257
color9   #B8645B
color10  #8EAD73
color11  #C59B58
color12  #668F92
color13  #88768F
color14  #89B49B
color15  #F0EBDD
